on:
  workflow_dispatch:
    inputs:
      tag:
        description: A release tag
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set release version
        run: echo "IMAGE_TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
        if: ${{ github.event.inputs.tag != '' }}

      - name: Build binaries
        run: make release

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.event.inputs.tag }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          name: dist-without-markdown
          path: |
            dist/*
        env:
          GITHUB_TOKEN: ${{ github.token }}
